# -*- coding: utf-8 -*-
"""Milli Mucadele Aydin Efeleri Agi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7k2iqgI8p5jvovk2muFqhuEyOPbOAti
"""

import matplotlib.pyplot as plt
import networkx as nx

# 1. Boş Ağ Yapısını Oluşturma
G = nx.Graph()

# 2. Tezinizden Çıkan Gerçek Düğümleri (Aktörleri) Ekleme
efeler = ["Yörük Ali Efe", "Demirci Mehmet Efe", "Kıllıoğlu Hüseyin Efe", "Danişmentli İsmail Efe"]
subaylar = ["Albay Refet Bey", "Miralay Şefik Bey", "Teğmen Zekai Bey"]
siyasiler_esraf = ["Celal Bayar\n(Galip Hoca)", "Esat İleri", "Müftü Hulusi Efendi"]

for efe in efeler: G.add_node(efe, type="Efe")
for subay in subaylar: G.add_node(subay, type="Subay")
for s in siyasiler_esraf: G.add_node(s, type="Siyasi/Eşraf")

# 3. Tezinizdeki Tarihsel İlişkileri (Bağlantıları) Ekleme
G.add_edge("Yörük Ali Efe", "Kıllıoğlu Hüseyin Efe", weight=5)
G.add_edge("Yörük Ali Efe", "Miralay Şefik Bey", weight=4)
G.add_edge("Yörük Ali Efe", "Celal Bayar\n(Galip Hoca)", weight=4)
G.add_edge("Yörük Ali Efe", "Demirci Mehmet Efe", weight=3)
G.add_edge("Demirci Mehmet Efe", "Albay Refet Bey", weight=5)
G.add_edge("Demirci Mehmet Efe", "Danişmentli İsmail Efe", weight=4)
G.add_edge("Miralay Şefik Bey", "Esat İleri", weight=4)
G.add_edge("Esat İleri", "Müftü Hulusi Efendi", weight=3)
G.add_edge("Teğmen Zekai Bey", "Yörük Ali Efe", weight=4)

# 4. Ağı Görselleştirme
plt.figure(figsize=(10, 8))
pos = nx.kamada_kawai_layout(G)

# Düğümleri çiziyoruz
nx.draw_networkx_nodes(G, pos, node_size=2500, node_color="#98FB98", linewidths=1)
# Bağlantıları çiziyoruz
nx.draw_networkx_edges(G, pos, width=[d["weight"] for u, v, d in G.edges(data=True)], edge_color="gray", alpha=0.6)
# İsimleri yazalım
nx.draw_networkx_labels(G, pos, font_size=9, font_family="sans-serif", font_weight="bold")

plt.title("Milli Mücadele'de Aydın Efeleri İlişki Ağı Haritası", fontsize=14, fontweight="bold", pad=20)
plt.axis("off")
plt.show()